# Generated by Django 3.0.4 on 2020-07-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='universities',
            field=models.ManyToManyField(blank=True, help_text='Select Universities involved', related_name='schools', to='main.University'),
        ),
        migrations.AddField(
            model_name='author',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.University'),
        ),
    ]
