# Generated by Django 3.0.4 on 2020-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Stage Name')),
                ('slug', models.SlugField(blank=True, help_text='Click on the name field to populate this field', max_length=200, null=True, unique=True)),
                ('image', models.ImageField(default='artist/default.jpg', upload_to='artist')),
                ('paid', models.BooleanField(default=False, help_text='Select if payment has been made to activate full artist card features', verbose_name='Artist Payment')),
                ('verified', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'In Review'), (1, 'Confirmed'), (2, 'Denied'), (3, 'Graduate')], default=0)),
                ('ig_page', models.CharField(blank=True, help_text='Required', max_length=200, null=True, verbose_name='Instagram account')),
                ('twitter_page', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='Twitter account')),
                ('itunes', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='iTunes Profile')),
                ('audiomack', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='Audiomack Profile')),
                ('soundcloud', models.CharField(blank=True, help_text='Optional', max_length=200, null=True, verbose_name='Soundcloud Profile')),
                ('category', models.ManyToManyField(blank=True, related_name='genre', to='artist.ArtistCategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
